### PR TITLE
Period combo box

### PR DESCRIPTION
**Pull request by mpele**
Added ability to user chose some of predefined time periods.

### CODE REVIEW

**Comment by vitalidze** [comment]
Thank you. Why there are so many lines changed in `ArchiveView.java`? I don't want to merge it because it will break the `blame` function of git.

**Comment by mpele** [comment]
It looks like that the indentation has been changed. Changes could be seen on link https://github.com/vitalidze/traccar-web/pull/223/files?w=1 .

How could it be corrected?

By the way, the blame function will still work if you use the trigger -w.

**Comment by vitalidze** [comment]
You can use interactive rebase, edit that commit and then push with '-f' option. 

P.S. I know about the '-w' option, but prefer to use it with defaults so I don't have to remember any triggers.

**Comment by vitalidze** [comment]
Actually I can do it myself, but it will be hard for you to merge your branch back in your repository. So you will have to delete yours and then merge latest changes from my `dev` branch. The author of commits will still be you. If it works for you I can do it.

**Comment by mpele** [comment]
It is OK for me.
Thank you Vitaly

**Comment by vitalidze** [comment]
Merged, you can delete your branch and try merging changes from my `dev` branch. I have done couple of changes as well:
- https://github.com/vitalidze/traccar-web/commit/9636570957e58f6d6e63484a9c402156f6a26ccf - removing `report` button, fixed indents. You had tabs instead of spaces.
- https://github.com/vitalidze/traccar-web/commit/180f4dddfd7bd973358500afe53ade8efed854f9 - removed informative popups flooding on each event from period combo box

**Pull request closed without merging**
