### PR TITLE
Language update for es_ES

### PR DESCRIPTION
**Pull request by j5boot**
Language update for es_ES

### CODE REVIEW

**Comment by vitalidze** [comment]
Thanks for the pull request. Can you also kindly update spanish messages for mobile version in this file https://github.com/vitalidze/traccar-web/blob/dev/src/main/webapp/m/js/i18n/Messages.js ?

**Comment by j5boot** [comment]
Done

**Comment by vitalidze** [comment]
Thank you.

**Comment by vitalidze** [comment]
Merged, written [news](http://traccar.litvak.su/2015/03/15/security-fix,-mobile-ui-script-links-fix-and-updated-spanish-translation.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

**Pull request merged**
