### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by pallavt**
Requires Java 7 due to string switch/case.

Even more refactoring can be done if Java 8 is used.

### CODE REVIEW

**Comment by vitalidze** [comment]
Thanks for pull request.

Moving to java 7 is not an option since many people still use java 6. I don't want to put this requirement just for switch...case with strings.

**Comment by pallavt** [comment]
Maybe have a poll to find out if users can switch to java 7?

**Comment by vitalidze** [comment]
I don't want to bother users with such polls. I bet not everyone may know which version do they use. I think it's better to move when original `traccar` project (backend collecting device data) moves to java 7. We have already discussed this here https://github.com/tananaev/traccar/issues/728 and still the situation hasn't changed.

Why do you want so hard to move to java7?

**Comment by vitalidze** [comment]
Any update on this?

**Pull request closed without merging**
