### PR TITLE
polish translation

### PR DESCRIPTION
**Pull request by bigoss**

### CODE REVIEW

**Comment by vitalidze** [comment]
Please see changes in #108 - for some reason another guy has sent me updated polish translation. I don't know any word in polish, so please help me merging both these work.

**Comment by vitalidze** [comment]
Merged, written [news](http://traccar.litvak.su/2015/03/10/improved-localization-and-read-only-users.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

**Comment by bigoss** [comment]
Hi,

I am trying to modify / use for traccar-beb neptune theme 
have added txt-theme-neptune.jar ti the classpath  (copied and in intellij add as library)
I can make with intellij but when it cones to building .jar with ./mvnw package
at test i got following error: [ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project traccar-web: GWT Module com.sencha.gxt.theme.neptune.Theme not found in project sources or resources.

Can you help?

Regards

Jaroslaw

**Comment by vitalidze** [comment]
First of all, in future, please open another issue for the questions that are not related with current pull request/issue.

Regarding your problem you should include it as maven dependency - (in `pom.xml` - add `<dependency>` entry) either from maven central (looks like it's [this one](http://search.maven.org/#search%7Cga%7C1%7Cneptune)) or you may include such artifact from local folder, for example like said in this [thread](http://stackoverflow.com/questions/22508433/how-to-add-maven-dependency-jar-file-from-the-lib-folder). The first way is preferred.

**Pull request merged**
