### PR TITLE
Update Messages.js

### PR DESCRIPTION
**Pull request by RobertBenedikt**
add Czech language

### CODE REVIEW

**Comment by vitalidze** [comment]
Thanks for translation. Looks like it contains only 'mobile' version translation. Do you plan to translate 'desktop' version as well?

**Comment by RobertBenedikt** [comment]
everything is translated

**Comment by vitalidze** [comment]
Can you put all changes to a single pull request?

**Comment by RobertBenedikt** [comment]
I'm sorry, I have already sent it as 5 requests.

**Comment by vitalidze** [comment]
I can close all these pull requests without merging. Then you can merge all them yourself to a single branch (say some new one, or `dev`) and send pull request from that branch. It will contain all changes (commits, etc.) in a single pull request.

**Comment by RobertBenedikt** [comment]
OK

**Pull request closed without merging**
