### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by RobertBenedikt**
Czech language

### CODE REVIEW

**Comment by vitalidze** [comment]
Thanks for the translation. I will remove changes to format and titles.

**Comment by RobertBenedikt** [comment]
I'm sorry, I made further adjustments for myself, I did not know that it is also apparent

**Comment by vitalidze** [comment]
No problem, just be prepared to lose them if you later merge some changes from my `dev` branch.

**Comment by vitalidze** [comment]
Merged, written [news](http://traccar.litvak.su/2015/06/24/czech-translation-and-couple-of-updates-on-user-accounts.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Pull request merged**
