### PR TITLE
Wrapper log

### PR DESCRIPTION
**Pull request by mpele**
Copy functionality of showing traccar.log in dialog for showing the wrapper.log .

### CODE REVIEW

**Comment by vitalidze** [comment]
First of all, thank you very much for the pull request.

I can see that it is almost fully copied and pasted from the code that is capable of viewing `tracker-server.log` file. Can you extract common parts? I suggest the following:
- use the same dialog class that will have a so-called 'LogHandler', which will be specified in constructor. It will be capable of loading log of specified size.
- for loading log file contents create a method in `DataServiceImpl` class. It will have the file name  and size arguments and will try to load desired file from multiple location using `RandomAccessFile`. Then from both actual API methods you can just call it.

Hope this will work for you.

**Comment by mpele** [comment]
Hi Vitaly,

I understand that this code doesn't satisfy your standards. Unfortunately,
I have very, very, very limited time available to contribute to this
project, and I would like to work on some other aspects.
Since, this code is not so important for regular users you could ignore
this pull request - at least for now.

I will open new issue for discussion of further activities.

**Comment by vitalidze** [comment]
These are not "my" standards, but a common practice to re-use existing code and to not copy and paste it. This is what I don't like in this pull request. The approach can be different from the one that I suggested, I don't insist. From my point of view it will not take so much time to re-factor the code.

Anyway, thank you for your time spending on this code. Let it be opened until refactoring is applied.

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.

**Pull request closed without merging**
