### PR TITLE
Implement features

### PR DESCRIPTION
**Pull request by antoniopaisfernandes**
1. Allow for track color (small and complete palette)
2. Allow for standard or reduce markers in archive plot
3. When device's grid is double clicked, it changes Archive combobox
4. Update i18n strings
5. Fixes issue #59 (Issue with automatic login)

### CODE REVIEW

**Comment by vitalidze** [comment]
Thank you for pull request. But I will merge it when I finish #57 and include all these features into release. I think this will be done on next week.

**Comment by antoniopaisfernandes** [comment]
OK. And feel free to change/re-factor whatever you want.

**Comment by vitalidze** [comment]
Merged. Thank you.

**Comment by vitalidze** [comment]
Written [news](http://traccar.litvak.su/2015/01/13/Notifications,-archive-styling-and-couple-minor-improvements.html), [article](http://traccar.litvak.su/features/archive-styling.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

**Pull request merged**
