### PR TITLE
Update Messages_es.properties

### PR DESCRIPTION
**Pull request by j5boot**
Updated notifications, style and filter dialogs.

### CODE REVIEW

**Comment by vitalidze** [comment]
Thank you. Will update latest official package and write news.

**Comment by vitalidze** [comment]
Written [news](http://traccar.litvak.su/2015/02/02/updated-spanish-translation.html), [article](http://traccar.litvak.su/features/spanish.html). Included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

**Comment by j5boot** [comment]
Probe in demo and detected a mistake in translation. Sorry. I do a new pull request.

**Comment by vitalidze** [comment]
Sure

**Pull request merged**
