### PR TITLE
event rules

### PR DESCRIPTION
**Pull request by StanislavKo**
Event customization (device, geo-fense, type, time, course) feature
traccar_pull_request

### CODE REVIEW

**Comment by warlockopy** [comment]
Hello, how do you make improvements on the GUI, a short guide maybe.
did you do it hard coding.

**Comment by vitalidze** [comment]
@warlockopy If "hard coding" means "writing code", then yes, he writes code to do the changes. There is no other way to make the changes. You can observe all changes for this pull request here: https://github.com/vitalidze/traccar-web/pull/468/files

**Comment by warlockopy** [comment]
I build it and works, any reference where to add translations values for this update.

**Comment by mpele** [comment]
Hi Vitaly,
What are the plans with notification system, and what are your thoughts - will this pull request be accepted?

**Comment by vitalidze** [comment]
@mpele actually I don't think it should be implemented this way. It looks good, but I thought about different implementation. My plan is to take these changes as the base for the implementation that I have in my mind.

P.S. sorry for the delay in response.

**Comment by condeitokako** [comment]
Updates next versión?

**Comment by ghost** [comment]
Hi @StanislavKo I have something in mind you can help me ?? It is about events and alarms.

**Comment by xewonder** [comment]
@StanislavKo 
Hi,

Did you ever get the "event rules" working? this is exacly what we need.

Please let me know. Thaks

**Comment by xewonder** [comment]
@condeitokako 
Hi,

Did you get anything going with events and alarms?

Please let me know. Thaks

**Comment by condeitokako** [comment]
@xewonder 

My system already has notifications to what you are looking for you can check:

187.190.109.14
user: demodemo
pass: demodemo

regars.

**Comment by xewonder** [comment]
HI,



Very nice but apart from the language, I can not see/create geofences.





Please advise







*From:* Itokako [mailto:notifications@github.com]
*Sent:* 01 July 2017 06:43
*To:* vitalidze/traccar-web <traccar-web@noreply.github.com>
*Cc:* xewonder <denis.dorigo@ddinternet.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [vitalidze/traccar-web] event rules (#468)



@xewonder <https://github.com/xewonder>

My system already has notifications to what you are looking for you can
check:

187.190.109.14
user: demodemo
pass: demodemo

regars.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vitalidze/traccar-web/pull/468#issuecomment-312407978>,
or mute the thread

**Comment by ghost** [comment]
@xewonder.

The geo and poi are in the right and left panel

**Comment by vitalidze** [comment]
Merged (with several changes). Thank you.

**Pull request merged**
